name:                binary-counter
version:             0.1.0.0
github:              "imjacobclark/haskell-binary-counter"
license:             MIT
author:              "Jacob Clark"
maintainer:          "jacob.jh.clark@googlemail.com"
copyright:           "2018 Jacob Clark"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/imjacobclark/binary-counter#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  binary-counter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - binary-counter

tests:
  binary-counter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - binary-counter
